version: '3.7'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    env_file:
      - ./edlinker-backend/.env
    ports:
      - 5431:5432
  backend:
    container_name: backend_app
    build:
      context: ./edlinker-backend/
      dockerfile: backend.Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - PGHOST=${DB_HOST}
      - PGUSER=${POSTGRES_USER}
      - PGPASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./edlinker-backend:/backend
      - ./edlinker-backend/vendor/bundle:/backend/vendor/bundle
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file:
      - ./edlinker-backend/.env