version: '3.7'

services:
  db:
    image: postgres
    volumes:
      - data-postgres:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5431:5432
  backend:
    container_name: backend_app
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"    
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file:
      - .env
volumes:
  bundle:
  data-postgres:
  
